name: "Actions for pull request synchronize"

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore: [stage**]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true